// Mocks generated by Mockito 5.4.4 from annotations
// in spira/test/feature/presentation/cubits/audio_recorder/audio_recorder_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i5;
import 'dart:ui' as _i9;

import 'package:audio_waveforms/audio_waveforms.dart' as _i7;
import 'package:flutter_sound/flutter_sound.dart' as _i3;
import 'package:flutter_sound_platform_interface/flutter_sound_recorder_platform_interface.dart'
    as _i4;
import 'package:logger/logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:permission_handler_platform_interface/permission_handler_platform_interface.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FlutterSoundRecorder].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSoundRecorder extends _i1.Mock
    implements _i3.FlutterSoundRecorder {
  MockFlutterSoundRecorder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  _i4.RecorderState get recorderState => (super.noSuchMethod(
        Invocation.getter(#recorderState),
        returnValue: _i4.RecorderState.isStopped,
      ) as _i4.RecorderState);

  @override
  bool get isRecording => (super.noSuchMethod(
        Invocation.getter(#isRecording),
        returnValue: false,
      ) as bool);

  @override
  bool get isStopped => (super.noSuchMethod(
        Invocation.getter(#isStopped),
        returnValue: false,
      ) as bool);

  @override
  bool get isPaused => (super.noSuchMethod(
        Invocation.getter(#isPaused),
        returnValue: false,
      ) as bool);

  @override
  void setLogLevel(_i2.Level? aLevel) => super.noSuchMethod(
        Invocation.method(
          #setLogLevel,
          [aLevel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordingData({_i5.Uint8List? data}) => super.noSuchMethod(
        Invocation.method(
          #recordingData,
          [],
          {#data: data},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateRecorderProgress({
    int? duration,
    double? dbPeakLevel,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateRecorderProgress,
          [],
          {
            #duration: duration,
            #dbPeakLevel: dbPeakLevel,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void openRecorderCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #openRecorderCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void closeRecorderCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #closeRecorderCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pauseRecorderCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #pauseRecorderCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resumeRecorderCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #resumeRecorderCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startRecorderCompleted(
    int? state,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #startRecorderCompleted,
          [
            state,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopRecorderCompleted(
    int? state,
    bool? success,
    String? url,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #stopRecorderCompleted,
          [
            state,
            success,
            url,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void log(
    _i2.Level? logLevel,
    String? msg,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [
            logLevel,
            msg,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i3.FlutterSoundRecorder?> openRecorder() => (super.noSuchMethod(
        Invocation.method(
          #openRecorder,
          [],
        ),
        returnValue: _i6.Future<_i3.FlutterSoundRecorder?>.value(),
      ) as _i6.Future<_i3.FlutterSoundRecorder?>);

  @override
  _i6.Future<void> closeRecorder() => (super.noSuchMethod(
        Invocation.method(
          #closeRecorder,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isEncoderSupported(_i3.Codec? codec) => (super.noSuchMethod(
        Invocation.method(
          #isEncoderSupported,
          [codec],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> setSubscriptionDuration(Duration? duration) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSubscriptionDuration,
          [duration],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> startRecorder({
    _i3.Codec? codec = _i3.Codec.defaultCodec,
    String? toFile,
    _i6.StreamSink<_i3.Food>? toStream,
    int? sampleRate = 16000,
    int? numChannels = 1,
    int? bitRate = 16000,
    int? bufferSize = 8192,
    bool? enableVoiceProcessing = false,
    _i4.AudioSource? audioSource = _i4.AudioSource.defaultSource,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startRecorder,
          [],
          {
            #codec: codec,
            #toFile: toFile,
            #toStream: toStream,
            #sampleRate: sampleRate,
            #numChannels: numChannels,
            #bitRate: bitRate,
            #bufferSize: bufferSize,
            #enableVoiceProcessing: enableVoiceProcessing,
            #audioSource: audioSource,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> stopRecorder() => (super.noSuchMethod(
        Invocation.method(
          #stopRecorder,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> pauseRecorder() => (super.noSuchMethod(
        Invocation.method(
          #pauseRecorder,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resumeRecorder() => (super.noSuchMethod(
        Invocation.method(
          #resumeRecorder,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool?> deleteRecord({required String? fileName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRecord,
          [],
          {#fileName: fileName},
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<String?> getRecordURL({required String? path}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecordURL,
          [],
          {#path: path},
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);
}

/// A class which mocks [PlayerController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerController extends _i1.Mock implements _i7.PlayerController {
  MockPlayerController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.UpdateFrequency get updateFrequency => (super.noSuchMethod(
        Invocation.getter(#updateFrequency),
        returnValue: _i7.UpdateFrequency.high,
      ) as _i7.UpdateFrequency);

  @override
  set updateFrequency(_i7.UpdateFrequency? _updateFrequency) =>
      super.noSuchMethod(
        Invocation.setter(
          #updateFrequency,
          _updateFrequency,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<double> get waveformData => (super.noSuchMethod(
        Invocation.getter(#waveformData),
        returnValue: <double>[],
      ) as List<double>);

  @override
  _i7.PlayerState get playerState => (super.noSuchMethod(
        Invocation.getter(#playerState),
        returnValue: _i7.PlayerState.initialized,
      ) as _i7.PlayerState);

  @override
  bool get shouldRefresh => (super.noSuchMethod(
        Invocation.getter(#shouldRefresh),
        returnValue: false,
      ) as bool);

  @override
  int get maxDuration => (super.noSuchMethod(
        Invocation.getter(#maxDuration),
        returnValue: 0,
      ) as int);

  @override
  String get playerKey => (super.noSuchMethod(
        Invocation.getter(#playerKey),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#playerKey),
        ),
      ) as String);

  @override
  bool get shouldClearLabels => (super.noSuchMethod(
        Invocation.getter(#shouldClearLabels),
        returnValue: false,
      ) as bool);

  @override
  _i6.Stream<_i7.PlayerState> get onPlayerStateChanged => (super.noSuchMethod(
        Invocation.getter(#onPlayerStateChanged),
        returnValue: _i6.Stream<_i7.PlayerState>.empty(),
      ) as _i6.Stream<_i7.PlayerState>);

  @override
  _i6.Stream<int> get onCurrentDurationChanged => (super.noSuchMethod(
        Invocation.getter(#onCurrentDurationChanged),
        returnValue: _i6.Stream<int>.empty(),
      ) as _i6.Stream<int>);

  @override
  _i6.Stream<List<double>> get onCurrentExtractedWaveformData =>
      (super.noSuchMethod(
        Invocation.getter(#onCurrentExtractedWaveformData),
        returnValue: _i6.Stream<List<double>>.empty(),
      ) as _i6.Stream<List<double>>);

  @override
  _i6.Stream<double> get onExtractionProgress => (super.noSuchMethod(
        Invocation.getter(#onExtractionProgress),
        returnValue: _i6.Stream<double>.empty(),
      ) as _i6.Stream<double>);

  @override
  _i6.Stream<void> get onCompletion => (super.noSuchMethod(
        Invocation.getter(#onCompletion),
        returnValue: _i6.Stream<void>.empty(),
      ) as _i6.Stream<void>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> preparePlayer({
    required String? path,
    double? volume,
    bool? shouldExtractWaveform = true,
    int? noOfSamples = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #preparePlayer,
          [],
          {
            #path: path,
            #volume: volume,
            #shouldExtractWaveform: shouldExtractWaveform,
            #noOfSamples: noOfSamples,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<double>> extractWaveformData({
    required String? path,
    int? noOfSamples = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractWaveformData,
          [],
          {
            #path: path,
            #noOfSamples: noOfSamples,
          },
        ),
        returnValue: _i6.Future<List<double>>.value(<double>[]),
      ) as _i6.Future<List<double>>);

  @override
  _i6.Future<void> startPlayer({
    _i7.FinishMode? finishMode = _i7.FinishMode.stop,
    bool? forceRefresh = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startPlayer,
          [],
          {
            #finishMode: finishMode,
            #forceRefresh: forceRefresh,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> pausePlayer() => (super.noSuchMethod(
        Invocation.method(
          #pausePlayer,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> stopPlayer() => (super.noSuchMethod(
        Invocation.method(
          #stopPlayer,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> release() => (super.noSuchMethod(
        Invocation.method(
          #release,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> setRate(double? rate) => (super.noSuchMethod(
        Invocation.method(
          #setRate,
          [rate],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> getDuration([_i7.DurationType? durationType]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDuration,
          [durationType],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> seekTo(int? progress) => (super.noSuchMethod(
        Invocation.method(
          #seekTo,
          [progress],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopAllPlayers() => super.noSuchMethod(
        Invocation.method(
          #stopAllPlayers,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRefresh(bool? refresh) => super.noSuchMethod(
        Invocation.method(
          #setRefresh,
          [refresh],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Permission].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockPermission extends _i1.Mock implements _i10.Permission {
  MockPermission() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: 0,
      ) as int);
}
